/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import basicSystem.ExtrLibrary;
import basicSystem.Helpme;
import help.bott;
import help.passwordfield;
import help.textfield;
import java.awt.Color;

/**
 *
 * @author en-mokhtar
 */
public class changepass extends javax.swing.JFrame {

    /**
     * Creates new form changepass
     */
    public changepass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grob = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        newuse = new textfield(20);
        newpass = new passwordfield(20);
        againpass = new passwordfield(20);
        rdnew = new javax.swing.JRadioButton();
        rdcurruse = new javax.swing.JRadioButton();
        label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botdelete = new bott();
        botedit = new bott();
        botadd = new bott();
        botback = new bott();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setText("Confirm password");

        newuse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        newuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuseActionPerformed(evt);
            }
        });

        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });

        againpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againpassActionPerformed(evt);
            }
        });

        rdnew.setText("New User ");
        rdnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdnewMouseClicked(evt);
            }
        });
        rdnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnewActionPerformed(evt);
            }
        });

        rdcurruse.setSelected(true);
        rdcurruse.setText("Current User");
        rdcurruse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdcurruseMouseClicked(evt);
            }
        });

        label.setText("Current user");

        jLabel4.setText("New password");

        botdelete.setText("Delete");
        botdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botdeleteActionPerformed(evt);
            }
        });

        botedit.setText("Edit");
        botedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boteditActionPerformed(evt);
            }
        });

        botadd.setText("Add");
        botadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaddActionPerformed(evt);
            }
        });

        botback.setText("back");
        botback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botadd)
                        .addGap(29, 29, 29)
                        .addComponent(botedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botdelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(againpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdcurruse)
                            .addComponent(rdnew))))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdnew)
                        .addGap(13, 13, 13)
                        .addComponent(rdcurruse))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(againpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botdelete)
                    .addComponent(botedit)
                    .addComponent(botadd))
                .addGap(28, 28, 28)
                .addComponent(botback)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newuseActionPerformed

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void againpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_againpassActionPerformed

    private void rdnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdnewMouseClicked
//        // TODO add your handling code here:
        newuse.setEnabled(true);
        label.setText("New User");
        botadd.setEnabled(true);
        botedit.setEnabled(false);
        botdelete.setEnabled(false);
//        newuse.setBackground(Color.white);
      clear();
       
    }//GEN-LAST:event_rdnewMouseClicked

    private void rdnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdnewActionPerformed
    public String use;
    public String pass;
    private void rdcurruseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdcurruseMouseClicked
//        // TODO add your handling code here:
        if(w!=1){
        botadd.setEnabled(false);
        label.setText("Current User");
        botdelete.setEnabled(true);
        botedit.setEnabled(true);
        newuse.setEnabled(false);
        clear();
        newuse.setBackground(Color.decode("#FDD017"));
        newuse.setText(use);
        newpass.requestFocus();}
    }//GEN-LAST:event_rdcurruseMouseClicked
    public void clear(){
        newuse.setText("");
        newpass.setText("");
        againpass.setText("");
        newuse.requestFocus();
    }
    int w=0;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        grob.add(rdnew);
        grob.add(rdcurruse);
        newuse.setText(use);
        rdcurruse.setBackground(Color.decode("#FDD017"));
        rdnew.setBackground(Color.decode("#FDD017"));
        if (w == 1) {
            label.setText("New User");
            botadd.setEnabled(true);
            rdcurruse.setEnabled(false);
            rdnew.setSelected(true);
            botback.setEnabled(false);
            botedit.setEnabled(false);
            botdelete.setEnabled(false);
        } else {
            botadd.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    @SuppressWarnings("UnusedAssignment")
    private void botaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaddActionPerformed
        // TODO add your handling code here:
        String g=newuse.getText();
        String h = newpass.getText();
        if (g.isEmpty()) {
            Helpme.error("Please Enter User Name");
            newuse.requestFocus();
        } else if (h.isEmpty()) {
            Helpme.error("Please Enter Password");
            newpass.requestFocus();
        } else if ((againpass.getText()).isEmpty()) {
            Helpme.error("Please Enter CConfirm Password");
            againpass.requestFocus();
        } else if (!h.equals(againpass.getText())) {
            Helpme.error("Password and Confirm are not equal ");
            newpass.setText("");
            againpass.setText("");
            newpass.requestFocus();
        } else {
            Object[] asd=new Object[2];
            asd[0]=g;
            asd[1]=h;
            ExtrLibrary.man.add(asd);
            clear(); 
            if(w==1){
                 jmansger m = new jmansger();
            Helpme.form(m, "Manager", "man.jpg");
            this.dispose();
            }
        }
        

    }//GEN-LAST:event_botaddActionPerformed

    private void botbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbackActionPerformed
        // TODO add your handling code here:
        jmansger h = new jmansger();
        Helpme.form(h, "Manager", "man.jpg");
        this.dispose();
    }//GEN-LAST:event_botbackActionPerformed

    private void boteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boteditActionPerformed
        // TODO add your handling code here:
        Object rowstring[]=new Object[2];
         String g=newuse.getText();
        String h=newpass.getText();
        rowstring[0] = use;
        rowstring[1] = pass;      
        int a=ExtrLibrary.man.test(rowstring);
        if(h.isEmpty()){
            Helpme.error("Please Enter Password");
            newpass.requestFocus();
        }
        else if((againpass.getText()).isEmpty()){
            Helpme.error("Please Enter CConfirm Password");
            againpass.requestFocus();}
        
        else if(!h.equals(againpass.getText())){
            Helpme.error("Password and Confirm are not equal ");
            newpass.setText("");
            againpass.setText("");
            newpass.requestFocus();
        }
        else{     
        ExtrLibrary.man.setName(use);
        ExtrLibrary.man.setPass(newpass.getText());
        ExtrLibrary.man.edit(a-1);
        clear();
        }
    }//GEN-LAST:event_boteditActionPerformed

    private void botdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botdeleteActionPerformed
        Object rowstring[] = new Object[2];
        rowstring[0] = use;
        rowstring[1] = pass;
        int s = ExtrLibrary.man.count(),a;
        switch(s){
            case 1: Helpme.error("you can not delete latest user");break;
        
            default:{ if (use.equals("")) {
            Helpme.error("No Current User");
            } else {
            a = ExtrLibrary.man.test(rowstring);
            ExtrLibrary.man.delete(a - 1);
            clear();
            use = "";
        }}}
    }//GEN-LAST:event_botdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField againpass;
    private javax.swing.JButton botadd;
    private javax.swing.JButton botback;
    private javax.swing.JButton botdelete;
    private javax.swing.JButton botedit;
    private javax.swing.ButtonGroup grob;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label;
    private javax.swing.JTextField newpass;
    private javax.swing.JTextField newuse;
    private javax.swing.JRadioButton rdcurruse;
    private javax.swing.JRadioButton rdnew;
    // End of variables declaration//GEN-END:variables
}
