/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static basicSystem.ExtrLibrary.run;
import static basicSystem.ExtrLibrary.borr;
import static basicSystem.ExtrLibrary.liter;
import static basicSystem.ExtrLibrary.bookalm;
import static basicSystem.ExtrLibrary.booklet;
import basicSystem.Helpme;
import basicSystem.fulltable;
import basicSystem.numberday;
import basicSystem.scientific;
import help.bott;
import help.textfield;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author en-mokhtar
 */
public class jstudent extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form jstudent
     */
    public jstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grob1 = new javax.swing.ButtonGroup();
        grob2 = new javax.swing.ButtonGroup();
        rdname = new javax.swing.JRadioButton();
        rdprice = new javax.swing.JRadioButton();
        rdwriter = new javax.swing.JRadioButton();
        searchbo = new textfield(15);
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numbo = new textfield(15);
        nameb0 = new textfield(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        booktable = new javax.swing.JTable();
        publisherbo = new textfield(15);
        jButton6 = new bott();
        writerbo = new textfield(15);
        pricebo = new textfield(15);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search = new bott();
        botreturn = new bott();
        botborrow = new bott();
        rdalm = new javax.swing.JRadioButton();
        rdadb = new javax.swing.JRadioButton();
        txtunit = new textfield(15);
        jLabel7 = new javax.swing.JLabel();
        rdbooklet = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rdname.setSelected(true);
        rdname.setText("name");

        rdprice.setText("price");

        rdwriter.setText("writer");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("search by:");

        jLabel4.setText("writer");

        jLabel5.setText("price");

        numbo.setEditable(false);
        numbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numboActionPerformed(evt);
            }
        });

        nameb0.setEditable(false);
        nameb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameb0ActionPerformed(evt);
            }
        });

        booktable.getTableHeader().setForeground(Color.black);
        booktable.getTableHeader().setBackground(Color.decode("#FDD017"));
        booktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Number", "Name", "Publisher", "Writer", "Price", "Units"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        booktable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booktableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(booktable);

        publisherbo.setEditable(false);
        publisherbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherboActionPerformed(evt);
            }
        });

        jButton6.setText("back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        writerbo.setEditable(false);
        writerbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writerboActionPerformed(evt);
            }
        });

        pricebo.setEditable(false);
        pricebo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceboActionPerformed(evt);
            }
        });

        jLabel1.setText("book number");

        jLabel2.setText("book name");

        jLabel3.setText("publisher");

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        botreturn.setText("return");
        botreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botreturnActionPerformed(evt);
            }
        });

        botborrow.setText("borrow");
        botborrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botborrowActionPerformed(evt);
            }
        });

        rdalm.setSelected(true);
        rdalm.setText("Book");
        rdalm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdalmMouseClicked(evt);
            }
        });

        rdadb.setText("Magazine");
        rdadb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdadbMouseClicked(evt);
            }
        });

        txtunit.setEditable(false);
        txtunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunitActionPerformed(evt);
            }
        });

        jLabel7.setText("Unit");

        rdbooklet.setText("booklet");
        rdbooklet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbookletMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameb0, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(writerbo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricebo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(publisherbo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numbo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton6)
                    .addComponent(botreturn)
                    .addComponent(botborrow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(search)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdprice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdwriter)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rdalm)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rdadb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdbooklet))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nameb0, numbo, pricebo, publisherbo, txtunit, writerbo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botborrow, botreturn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(rdname)
                                .addComponent(rdwriter)
                                .addComponent(rdprice)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdalm)
                            .addComponent(rdadb)
                            .addComponent(rdbooklet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(numbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameb0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisherbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(writerbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pricebo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addComponent(botborrow)
                        .addGap(18, 18, 18)
                        .addComponent(botreturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nameb0, numbo, pricebo, publisherbo, txtunit, writerbo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botborrow, botreturn});

        rdname.setBackground(Color.decode("#FDD017"));
        rdprice.setBackground(Color.decode("#FDD017"));
        rdwriter.setBackground(Color.decode("#FDD017"));
        rdprice.setBackground(Color.decode("#FDD017"));
        rdprice.setBackground(Color.decode("#FDD017"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numboActionPerformed
    public String stud;
    public String level;
  
     
    private void nameb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameb0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameb0ActionPerformed

    private void publisherboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherboActionPerformed

    private void writerboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writerboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_writerboActionPerformed

    private void priceboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceboActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          library b = new library();
        run(b);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String f = search.getText();
        int o;
        if (rdalm.isSelected()) {
            o = bookalm.count();
        } else {
            o = liter.count();
        }

        Object[][] w = new Object[o][6];
        if (f.isEmpty()) {
            Helpme.error("Enter Word for Search");
            search.requestFocus();
        } else if (rdalm.isSelected()) {
            if (rdname.isSelected()) {
                w = bookalm.search(1, f);
            } else if (rdwriter.isSelected()) {
                w = bookalm.search(3, f);
            } else {
                w = bookalm.search(4, f);
            }

        } else if (rdadb.isSelected()) {
            if (rdname.isSelected()) {
                w = liter.search(1, f);
            } else if (rdwriter.isSelected()) {
                w = liter.search(3, f);
            } else {
                w = liter.search(4, f);
            }

        }else if(rdbooklet.isSelected()){
            if (rdname.isSelected()) {
                w = booklet.search(1, f);
            } else if (rdwriter.isSelected()) {
                w = booklet.search(3, f);
            } else {
                w = booklet.search(4, f);
            }
        }
        fulltable.fullalldata(w, booktable);

    }//GEN-LAST:event_searchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        grob1.add(rdadb);
        grob1.add(rdbooklet);
        grob1.add(rdalm);
        grob2.add(rdname);
        grob2.add(rdwriter);
        grob2.add(rdprice);
       // botborrow.setEnabled(false);
       // botreturn.setEnabled(false);
         rdalm.setBackground(Color.decode("#FDD017"));
        rdadb.setBackground(Color.decode("#FDD017"));
        rdbooklet.setBackground(Color.decode("#FDD017"));
        fulltable.fullalldata(bookalm.getdata(), booktable);
        

    }//GEN-LAST:event_formWindowOpened

    private void botborrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botborrowActionPerformed
        Date date=new Date();
        SimpleDateFormat format=new SimpleDateFormat("dd/MM/yyyy");
        String currentdate=format.format(date);
        String book = nameb0.getText();
        if(book.isEmpty()){
            Helpme.error("Please Select book");
        }
        else{
        String d;              
        Object doo3[] = new Object[4];
        Object doo[] = new Object[5];
        Object doo2[] = new Object[6];
        doo3[0] = level;
        doo3[1] = stud;
        doo3[2] = book;
        doo3[3] = ""; 
        doo[0] = level;
        doo[1] = stud;
        doo[2] = book;
        doo[3]=currentdate;
        doo[4] = ""; 
        doo2[0] = numbo.getText();
        doo2[1] = nameb0.getText();
        doo2[2] = publisherbo.getText();
        doo2[3] = writerbo.getText();
        doo2[4] = pricebo.getText();
        doo2[5] = txtunit.getText();
        int z, l, x;
        if (rdalm.isSelected()) {
            z = borr.searchb(doo3);
            x = bookalm.search(doo2);
            d = (String) bookalm.unit(x - 1);
            l = Integer.parseInt(d);
            clear();
        } else if(rdadb.isSelected()) {
            z = borr.search(doo3);
            x = liter.search(doo2);
            d = (String) liter.unit(x - 1);
            l = Integer.parseInt(d);
            clear();
        }else {
             z = borr.search(doo3);
            x = booklet.search(doo2);
            d = (String) booklet.unit(x - 1);
            l = Integer.parseInt(d);
            clear();
            fullbooklet();
            
        }
        if (z > 0) {
            Helpme.error("you are booked this book!");
        } else if (l == 0) {
            Helpme.error("All Copies are booked!");
        } else if (rdalm.isSelected()) {
            l--;
            bookalm.edit(x - 1, String.valueOf(l));
            borr.setDoo(doo);
            borr.addtake();
            fullalm();
        } else if (rdadb.isSelected()) {
            l--;
            liter.edit(x - 1, String.valueOf(l));
            borr.setDoo(doo);
            borr.addtake();
            fulladb();
        }else if(rdbooklet.isSelected()){
            l--;
            booklet.edit(x - 1, String.valueOf(l));
            borr.setDoo(doo);
            borr.addtake();
            fullbooklet();
        }
        }
    }//GEN-LAST:event_botborrowActionPerformed
    public void fullalm() {
        fulltable.fullalldata(bookalm.getdata(), booktable);
    }

    public void fulladb() {
        fulltable.fullalldata(liter.getdata(), booktable);
    }

    public void fullbooklet() {
        fulltable.fullalldata(booklet.getdata(), booktable);
    }

    
    private void booktableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booktableMouseClicked
        // TODO add your handling code here:
        int row = booktable.getSelectedRow();
        String num = booktable.getValueAt(row, 0).toString();
        String name = booktable.getValueAt(row, 1).toString();
        String publ = booktable.getValueAt(row, 2).toString();
        String writ = booktable.getValueAt(row, 3).toString();
        String price = booktable.getValueAt(row, 4).toString();
        String unit = booktable.getValueAt(row, 5).toString();
        numbo.setText(num);
        nameb0.setText(name);
        publisherbo.setText(publ);
        writerbo.setText(writ);
        pricebo.setText(price);
        txtunit.setText(unit);
       // botborrow.setEnabled(true);

      
    }//GEN-LAST:event_booktableMouseClicked
     public void clear() {
        numbo.setText("");
        nameb0.setText("");
        publisherbo.setText("");
        writerbo.setText("");
        pricebo.setText("");
        txtunit.setText("");
    }
    private void txtunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunitActionPerformed

    private void botreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botreturnActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String currentdate = format.format(date);
        numberday dayy = new numberday();
        int days = -1;
        String book = nameb0.getText();
        String aa;
        if (book.isEmpty()) {
            Helpme.error("Please Select book");
        } else {
            Object doo3[] = new Object[4];
            Object doo[] = new Object[5];

            doo3[0] = level;
            doo3[1] = stud;
            doo3[2] = book;
            doo3[3] = "";

            doo[0] = level;
            doo[1] = stud;
            doo[2] = book;

            int z = borr.searchb(doo3), l;
            if (z > 0) {
                if (rdalm.isSelected()) {
                    returnn(bookalm);

                } else if (rdadb.isSelected()) {
                    returnn(liter);
                } else if (rdbooklet.isSelected()) {
                    returnn(booklet);
                }
                aa = (String) (borr.unit(z - 1, 3));
                doo[3] = aa;
                days = dayy.datea(aa);
                doo[4] = currentdate;
                borr.setDoo(doo);
                borr.addreturn(z - 1);
            } else {
                Helpme.error("you are not borrowing this book!");
            }

        }
        if (days == 0) {
            Helpme.error("you are return book in the same day");
        } else if (days >= 10) {
            Helpme.error("you are return abook after ten days you should pay atax");
            String a = "you are return abook in " + String.valueOf(days) + " days";
            Helpme.error(a);
        } else if (days > 0 && days < 10) {
            String a = "you are return abook in " + String.valueOf(days) + " days";
            Helpme.error(a);
        }
        clear();
    }//GEN-LAST:event_botreturnActionPerformed
    public void returnn(scientific r){
         Object doo2[] = new Object[6];
         doo2[0] =numbo.getText();
        doo2[1] =nameb0.getText();
        doo2[2] =publisherbo.getText();
        doo2[3] =writerbo.getText();
        doo2[4] =pricebo.getText();
        doo2[5] =txtunit.getText();
          int x=r.search(doo2),l;
           String book=(String) r.unit(x-1);
           l=Integer.parseInt(book);
           ++l;
           r.edit(x-1, String.valueOf(l));
           fulltable.fullalldata(r.getdata(), booktable);
           
    }
    private void rdadbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdadbMouseClicked
        // TODO add your handling code here:       
        fulladb();
    }//GEN-LAST:event_rdadbMouseClicked

    private void rdalmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdalmMouseClicked
        // TODO add your handling code here:
        fullalm();
    }//GEN-LAST:event_rdalmMouseClicked

    private void rdbookletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbookletMouseClicked
        // TODO add your handling code here:
        fullbooklet();
    }//GEN-LAST:event_rdbookletMouseClicked

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booktable;
    private javax.swing.JButton botborrow;
    private javax.swing.JButton botreturn;
    private javax.swing.ButtonGroup grob1;
    private javax.swing.ButtonGroup grob2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameb0;
    private javax.swing.JTextField numbo;
    private javax.swing.JTextField pricebo;
    private javax.swing.JTextField publisherbo;
    private javax.swing.JRadioButton rdadb;
    private javax.swing.JRadioButton rdalm;
    private javax.swing.JRadioButton rdbooklet;
    private javax.swing.JRadioButton rdname;
    private javax.swing.JRadioButton rdprice;
    private javax.swing.JRadioButton rdwriter;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchbo;
    private javax.swing.JTextField txtunit;
    private javax.swing.JTextField writerbo;
    // End of variables declaration//GEN-END:variables
}
